server:
  port: 8089
spring:
  cloud:
    ssl:
      enable: false
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        cluster-name: SH
  application:
    name: userservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:4306/cloud_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mingaox
    password: minx527527@
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
