server:
  port: 8084

spring:
  cloud:
    ssl:
      enable: false
    openfeign:
      client:
        config:
          default:
            loggerLevel: BASIC
      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 10
    nacos:
#      server-addr: localhost:8848
      discovery:
        cluster-name: SH
        server-addr: localhost:8848
        namespace: 6a0c5c98-8b81-49f4-942d-4413fe50cee1 # 配置环境（可用于区分dev、test、生产）--环境隔离，不同环境的服务无法调用
        ephemeral: false #是否临时事例 true是，false非临时事例
  application:
    name: orderervice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:4306/cloud_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mingaox
    password: minx527527@

  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
# 要配置的微服务名称
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

# application.yml or bootstrap.yml
#ribbon:
#  # 设置负载均衡策略为 ZoneAvoidanceRule（优先选择同一区域的节点）
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule